version: '3.8'

services:
  app-dev:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  app-prod:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
